//
// Created by Marthel Rodriguez on 11/29/23.
//

#ifndef SFMLTEMPLATE_SCREENENUM_H
#define SFMLTEMPLATE_SCREENENUM_H

enum screenEnum {HOME, POKEMON};

enum pokemonScreenElementsEnum {SPRITEDISPLAY, DESCRIPTION, EVOLUTIONS, POKEMON_TYPES, POKEMONWEAKNESS, LAST_POKEMON_SCREEN_ELEMENT};

enum homeScreenElementsEnum{SEARCHINPUT, FILTER1, FILTER2, FILTER3, GRIDBUTTON, LAST_HOME_SCREEN_ELEMENT};

#endif //SFMLTEMPLATE_SCREENENUM_H
