//
// Created by Marthel Rodriguez on 11/29/23.
//

#ifndef SFMLTEMPLATE_SCREENENUM_H
#define SFMLTEMPLATE_SCREENENUM_H

enum screenEnum {HOME, POKEMON};

enum pokemonScreenElementsEnum {SPRITE_DISPLAY, DESCRIPTION, EVOLUTIONS, POKEMON_TYPES, POKEMON_WEAKNESS, LAST_POKEMON_SCREEN_ELEMENT};

enum homeScreenElementsEnum{SEARCH_INPUT, FILTER1, FILTER2, FILTER3, GRID_BUTTON, LAST_HOME_SCREEN_ELEMENT};

#endif //SFMLTEMPLATE_SCREENENUM_H
